name: Docker Setup
description: Common steps for Docker jobs
inputs:
  registry:
    required: true
    description: container registry domain
    default: ghcr.io
  username:
    required: true
    description: container registry username
  password:
    required: true
    description: container registry password
outputs:
  meta_json:
    description: metadata json
    value: ${{ steps.meta.outputs.json }}
  meta_labels:
    description: metadata labels
    value: ${{ steps.meta.outputs.labels }}
  meta_version:
    description: metadata version
    value: ${{ steps.meta.outputs.version }}
runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        labels: |
          org.opencontainers.image.title="BentoBox"
          org.opencontainers.image.description="Open Source Inventory Management"
